- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    creationTimestamp: "2023-11-10T13:20:13Z"
    generation: 1
    labels:
      monitoring-key: middleware
      prometheus: application-monitoring
      role: alert-rules
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:monitoring-key: {}
            f:prometheus: {}
            f:role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"1c638751-0600-4702-827c-6a507f1dc9e5"}: {}
        f:spec:
          .: {}
          f:groups:
            .: {}
            k:{"name":"general.rules"}:
              .: {}
              f:name: {}
              f:rules: {}
      manager: keycloak-operator
      operation: Update
      time: "2023-11-10T13:20:13Z"
    name: keycloak
    namespace: knime
    ownerReferences:
    - apiVersion: keycloak.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Keycloak
      name: knime-keycloak
      uid: 1c638751-0600-4702-827c-6a507f1dc9e5
    resourceVersion: "5472"
    uid: 1406e932-8d02-435b-bca4-60f1df07601d
  spec:
    groups:
    - name: general.rules
      rules:
      - alert: KeycloakJavaNonHeapThresholdExceeded
        annotations:
          message: '{{ printf "%0.0f" $value }}% nonheap usage of {{ $labels.area
            }} in pod {{ $labels.pod }}, namespace {{ $labels.namespace }}.'
        expr: 100 * jvm_memory_bytes_used{area="nonheap",namespace="knime"} / jvm_memory_bytes_max{area="nonheap",namespace="knime"}
          > 90
        for: 1m
        labels:
          severity: warning
      - alert: KeycloakJavaGCTimePerMinuteScavenge
        annotations:
          message: Amount of time per minute spent on garbage collection of {{ $labels.area
            }} in pod {{ $labels.pod }}, namespace {{ $labels.namespace }} exceeds
            90%. This could indicate that the available heap memory is insufficient.
        expr: increase(jvm_gc_collection_seconds_sum{gc="PS Scavenge",namespace="knime"}[1m])
          > 1 * 60 * 0.9
        for: 1m
        labels:
          severity: warning
      - alert: KeycloakJavaGCTimePerMinuteMarkSweep
        annotations:
          message: Amount of time per minute spent on garbage collection of {{ $labels.area
            }} in pod {{ $labels.pod }}, namespace {{ $labels.namespace }} exceeds
            90%. This could indicate that the available heap memory is insufficient.
        expr: increase(jvm_gc_collection_seconds_sum{gc="PS MarkSweep",namespace="knime"}[1m])
          > 1 * 60 * 0.9
        for: 1m
        labels:
          severity: warning
      - alert: KeycloakJavaDeadlockedThreads
        annotations:
          message: Number of threads in deadlock state of {{ $labels.area }} in pod
            {{ $labels.pod }}, namespace {{ $labels.namespace }}
        expr: jvm_threads_deadlocked{namespace="knime"} > 0
        for: 1m
        labels:
          severity: warning
      - alert: KeycloakLoginFailedThresholdExceeded
        annotations:
          message: More than 50 failed login attempts for realm {{ $labels.realm }},
            provider {{ $labels.provider }}, namespace {{ $labels.namespace }} over
            the last 5 minutes. (Rate of {{ printf "%0f" $value }})
        expr: rate(keycloak_failed_login_attempts{namespace="knime"}[5m]) * 300 >
          50
        for: 5m
        labels:
          severity: warning
      - alert: KeycloakInstanceNotAvailable
        annotations:
          message: Keycloak instance in namespace {{ $labels.namespace }} has not
            been available for the last 5 minutes.
        expr: (1 - absent(kube_pod_status_ready{namespace="knime", condition="true"}
          * on (pod) group_left (label_component) kube_pod_labels{label_component="keycloak",
          namespace="knime"})) == 0
        for: 5m
        labels:
          severity: critical
      - alert: KeycloakAPIRequestDuration90PercThresholdExceeded
        annotations:
          message: More than 10% the RH SSO API endpoints in namespace {{ $labels.namespace
            }} are taking longer than 1s for the last 5 minutes.
        expr: (sum(rate(keycloak_request_duration_bucket{le="1000.0", namespace="knime"}[5m]))
          by (job) / sum(rate(keycloak_request_duration_count{namespace="knime"}[5m]))
          by (job)) < 0.90
        for: 5m
        labels:
          severity: warning
      - alert: KeycloakAPIRequestDuration99.5PercThresholdExceeded
        annotations:
          message: More than 0.5% of the RH SSO API endpoints in namespace {{ $labels.namespace
            }} are taking longer than 10s for the last 5 minutes.
        expr: (sum(rate(keycloak_request_duration_bucket{le="10000.0", namespace="knime"}[5m]))
          by (job) / sum(rate(keycloak_request_duration_count{namespace="knime"}[5m]))
          by (job)) < 0.995
        for: 5m
        labels:
          severity: warning
